version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: cheese321-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 251625
      POSTGRES_DB: cheese321
    ports:
      - "5433:5432" #도커는 5433 로컬은 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: