spring:
  application:
    name: cheese321
  profiles:
    group:
      local:
        - common-local
      prod:
        - common-prod
    active: local

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true