spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: false

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:20MB}

# 로그 설정
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.hsmile.cheese321: ${LOG_LEVEL_APP:INFO}
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
  file:
    name: ${LOG_FILE_PATH:/logs/cheese321.log}

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_VALIDITY:3600000}
  refresh-token-validity: ${JWT_REFRESH_VALIDITY:2592000000}

# AI 추천 서비스
app:
  ai-service:
    base-url: ${AI_SERVICE_URL:http://ai-service:8081}
    timeout: ${AI_SERVICE_TIMEOUT:30}
    use-dummy: ${AI_USE_DUMMY:false}

# 서버 설정
server:
  port: ${SERVER_PORT:8080}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics,prometheus}
      base-path: /actuator
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:when-authorized}
  metrics:
    tags:
      application: ${spring.application.name}
      environment: prod
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}

# Swagger
springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false} #비활
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

# 앱 정보
info:
  app:
    name: cheese321
    description: hsmile-cheese
    version: ${APP_VERSION:0.0.1-SNAPSHOT}