spring:
  datasource:
    url: jdbc:postgresql://google/cheese321?cloudSqlInstance=cheese321-demo:asia-northeast3:cheese321-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1q2w3e4r
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgreSQLDialect
        format_sql: false
        default_schema: cheese_core

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

# 로그 설정
logging:
  level:
    root: INFO
    com.hsmile.cheese321: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
  file:
    name: /logs/cheese321.log

# JWT 설정
jwt:
  secret: Y2hlZXNlMzIxLWp3dC1zZWNyZXQta2V5LWZvci1oLXNtaWxlLXBob3RvYm9vdGgtYXBwLTIwMjUtc2VjdXJlLWtleS1mb3ItcHJvZHVjdGlvbg==
  access-token-validity: 3600000
  refresh-token-validity: 2592000000

# 추천 서비스
app:
  ai-service:
    base-url: http://ai-service:8081
    timeout: 30
    use-dummy: true

# 서버 설정
server:
  port: 8080

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: cheese321
      environment: prod
    export:
      prometheus:
        enabled: true

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# 앱 정보
info:
  app:
    name: cheese321
    description: hsmile-cheese
    version: 0.0.1-SNAPSHOT