spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cheese321
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 251625

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: true

logging:
  level:
    root: INFO
    com.hsmile.cheese321: DEBUG
    org.hibernate.SQL: DEBUG