spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cheese321
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 251625

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: true

logging:
  level:
    root: INFO
    com.hsmile.cheese321: DEBUG
    org.hibernate.SQL: DEBUG

# JWT 설정
jwt:
  secret: "Y2hlZXNlMzIxLWp3dC1zZWNyZXQta2V5LWZvci1oLXNtaWxlLXBob3RvYm9vdGgtYXBwLTIwMjUtc2VjdXJlLWtleS1mb3ItcHJvZHVjdGlvbg=="
  access-token-validity: 3600000  # 1시간 (밀리초)
  refresh-token-validity: 2592000000  # 30일 (밀리초)