spring:
  datasource:
    # Docker 환경에서는 환경변수로 받기
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/cheese321}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:251625}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: true

# 로그 설정
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.hsmile.cheese321: ${LOG_LEVEL_APP:DEBUG}
    org.hibernate.SQL: DEBUG
    # Security 디버깅
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.web.access: DEBUG
    # Web 요청 디버깅
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    # JWT 필터 디버깅
    com.hsmile.cheese321.api.common.security: TRACE

# JWT 설정
jwt:
  secret: ${JWT_SECRET:Y2hlZXNlMzIxLWp3dC1zZWNyZXQta2V5LWZvci1oLXNtaWxlLXBob3RvYm9vdGgtYXBwLTIwMjUtc2VjdXJlLWtleS1mb3ItcHJvZHVjdGlvbg==}
  access-token-validity: 3600000  # 1시간 (밀리초)
  refresh-token-validity: 2592000000  # 30일 (밀리초)

# 추천서비스 연결
app:
  ai-service:
    base-url: ${AI_SERVICE_BASE_URL:http://localhost:8081}
    timeout: ${AI_SERVICE_TIMEOUT:10}
    use-dummy: ${AI_USE_DUMMY:true}

  # CORS 설정 추가 (React Native용 8081 포트 포함)
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001,http://localhost:8081,http://127.0.0.1:3000,http://127.0.0.1:8081,http://10.0.2.2:8080}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,PATCH,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    max-age: ${CORS_MAX_AGE:3600}


# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        # 개발환경에서는 모든 엔드포인트 노출
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always  # 헬스체크 상세 정보 표시
      show-components: always
    metrics:
      enabled: true
  health:
    # 개별 헬스체크 활성화
    defaults:
      enabled: true
    db:
      enabled: true  # 데이터베이스 상태 체크
    diskspace:
      enabled: true  # 디스크 공간 체크
  # 애플리케이션 정보
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  # 메트릭 설정
  metrics:
    tags:
      application: ${spring.application.name}
      environment: local
    export:
      prometheus:
        enabled: true  # 프로메테우스 메트릭 활성화

# 애플리케이션 정보 (Actuator info 엔드포인트용)
info:
  app:
    name: cheese321
    description: hsmile-cheese321
    version: 0.0.1-SNAPSHOT
    developer: pop