spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cheese321
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 251625
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.hsmile.cheese321: DEBUG
    org.hibernate.SQL: DEBUG