# .github/workflows/deploy.yml
name: Deploy to GCP Cloud Run

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG="asia-northeast3-docker.pkg.dev/cheese321-demo/cheese321-repo/backend:${{ github.sha }}"
          docker build -f .deploy/Dockerfile-prod -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cheese321-backend \
            --image=asia-northeast3-docker.pkg.dev/cheese321-demo/cheese321-repo/backend:${{ github.sha }} \
            --region=asia-northeast3 \
            --platform=managed \
            --allow-unauthenticated \
            --port=8080 \
            --memory=2Gi \
            --timeout=900 \
            --add-cloudsql-instances=cheese321-demo:asia-northeast3:cheese321-db \
            --set-env-vars="SPRING_PROFILES_ACTIVE=prod"